import type {EventChoice,PersonRole} from './types'
export const firstNames=['Amara','Theo','Nadia','Felix','Imani','Rowan','Celia','Jude','Anika','Owen','Priya','Kit','Elena','Miles','Sasha','Dev','Aisling','Ronan','Siobhan','Kwame','Mei','Haruto','Sofia','Luca','Inés','Mateo','Zara','Bilal','Niamh','Callum','Aoife','Darius','Talia','Hannah','Noah','Samira','George','Leila','Oscar','Marta','Javier','Adrian','Beatrice','Freddie','Rosa','Yasmin','Patrick','Claire'];
export const lastNames=['Okafor','Chen','Hart','Navarro','Price','Bennett','Khan','Sato','Doyle','Adebayo','Flynn','Costa','Shaw','Brooks','O’Sullivan','Murphy','Campbell','Patel','Mensah','Williams','Hughes','Reid','Ibrahim','Moretti','Rossi','Alvarez','Santos','Park','Tanaka','Laurent','Dubois','Nowak','Kowalski','Silva','Rahman','Foster','Murray','Clarke','Byrne','Walsh','Evans','Morgan','Turner','Ndlovu','Bouchard','Diaz','Kim','Haddad'];
export const titles=['The Low Road','Everything We Owe','Pale December','A House in Deptford','Second Unit','Good Behaviour','The Orchard Wall','Four Stops Home','Salt Country','Ordinary Damage','The Ballad of June Bell','Static Season','A Useful Lie','Dogs at the Wedding','Small Mercies','The Long Weekend','Blackwater County','The Committee','After the Floodlights','No Fixed Address','The Astronaut’s Sister','Sunday Service','The Last Bus to Galway','Dead Air','Milk Teeth','The Cartographer','Borrowed Weather','Half Past Summer','The Quiet Majority','Golden Hour','A Very Public Mistake','The Night Ferry','Seven Rooms','Common Ground','Red Hands','The Glass Province','Minor Characters','Northbound','The Emperor of Lewisham','Bright Objects'];
export const genres=[['Drama','Social realism'],['Comedy','Workplace comedy'],['Romantic comedy','Second-chance romance'],['Crime','Police procedural'],['Gangster','Period crime'],['Thriller','Conspiracy thriller'],['Psychological thriller','Domestic noir'],['Horror','Folk horror'],['Supernatural horror','Haunting'],['Historical','Court drama'],['Western','Revisionist western'],['Science fiction','Near-future drama'],['Fantasy','Dark folklore'],['Action','Contained action'],['Adventure','Survival adventure'],['War','Home-front drama'],['Mystery','Closed-room mystery'],['Satire','Political satire'],['Family drama','Intergenerational drama'],['Political drama','Westminster drama'],['Musical','Backstage musical'],['Experimental / arthouse','Nonlinear drama']];
export const studios=['BBC One','Channel 4','ITV Studios','Sky Atlantic','Film4','BFI / North Quay','Netflix UK','Amazon MGM','A24','Focus Features','Searchlight Pictures','HBO','Apple TV+','StudioCanal','Working Title','Left Bank Pictures','Bad Wolf','Warp Films','Element Pictures','Neon','Lionsgate','Universal Pictures'];
export const roles=['Jamie Buckley','Dr Samira Lowe','PC Daniel Hargreaves','Nina Costa','Elliot Reed','Maya Khan','Tommy O’Rourke','Councillor Imogen Shaw','Luis Ortega','Bea Okafor','Nathan Clarke','Asha Patel','Frankie Doyle','Yuki Tanaka','Mara Hughes','Jon Bell','Cerys Morgan','Alma Rossi','Noor Rahman','Callum Byrne'];
export const roleDescriptions=['a warehouse supervisor hiding a ruinous family secret','an ambitious junior barrister whose certainty begins to crack','the neighbour who saw more than they admit','a paramedic with a dangerously dry sense of humour','a campaign aide asked to bury the wrong story','an estranged sibling returning for a funeral','a scientist trying to expose their own mistake','a charming suspect who keeps changing their alibi','a teacher holding a chaotic family together','a musician confronting the career they abandoned'];
export const scripts=['Very strong dialogue. The final act is less convincing.','Lean, specific and genuinely funny; the ending is still moving around.','Ambitious and occasionally brilliant. Your agent worries it may be exhausting.','A solid genre script with a surprisingly human middle.','Polished, commercial and safer than anyone will admit.','Raw and observant; financed on what appears to be loose change.','The character is thin on the page but has one extraordinary scene.','A page-turner with a plot hole large enough to park a unit van in.','Odd, tender and either a festival hit or completely unreleasable.','The rewrite has dulled some edges, though the central relationship still works.'];
export const agentReads=['“The strongest acting material this month, though it is another bleak Tuesday in Britain.”','“Not glamorous, but the director gets good work out of people.”','“They have money, a release plan and absolutely no ending.”','“A small part. Two scenes. Both could get remembered.”','“This might be special. It might also play to fourteen people in Rotterdam.”','“You are not the obvious choice, which is exactly why I sent the tape.”','“Commercial, well paid and unlikely to trouble the history books.”','“Read it before judging the title. I have already judged the title.”'];
export const loglines=['After a teenager disappears on a wet night, a family turns on the one person trying to keep them together.','A council clerk discovers a routine planning application is connected to a death everyone has agreed to forget.','Two former friends are trapped together when a ferry breaks down halfway across the Irish Sea.','A disgraced journalist follows an anonymous tip into a town preparing for an unusually tense summer fête.','Three siblings clearing their mother’s house find a cassette that changes what they remember about childhood.','When a satellite falls silent, the engineer who designed it has one weekend to prove the fault was deliberate.','An understudy gets the lead on opening night and realises the company would prefer them to fail.','A rookie detective’s first murder case points uncomfortably close to the station itself.','A wedding weekend unravels when the best man arrives with somebody else’s dog and a damaging secret.','An exhausted minister tries to survive one news cycle after an offhand joke becomes a constitutional crisis.'];
export const reviewSnippets=['“A modest film with unusually sharp elbows.”','“The middle drags, but the final scene earns its silence.”','“A confident performance in a picture that never quite decides what it is.”','“Funny, bruising and refreshingly uninterested in easy answers.”','“The production is lavish; the emotional logic less so.”','“One of the few things here that feels recognisably human.”','“A surprising genre pleasure, assembled with wit rather than money.”','“Everyone involved deserved a better third act.”','“The lead work is precise without advertising its precision.”','“A beautiful failure that may gather loyal defenders.”'];
export const auditionNotes=['The director thinks the read is too controlled and wants more anger.','Casting likes the humour, but wonders if the character feels dangerous enough.','Your scene partner has changed the pace completely in the room.','The producer asks for the scene “warmer” without being able to explain what that means.','The director wants you to drop the accent you prepared.','You learn the role is being rewritten younger and more openly comic.'];
export const auditionChoices:EventChoice[]=[
 {label:'Give the note cleanly',detail:'Show them the version they asked for, without decorating it.',consequence:'The room appreciates the clarity, though some of your original texture disappears.',performance:2,relationship:5,industry:2,film:0},
 {label:'Adjust, but keep the restraint',detail:'Move toward the note while protecting what made your first read specific.',consequence:'It is a riskier read. The director leans forward; the producer does not.',performance:6,relationship:0,industry:0,film:0},
 {label:'Ask what the character is hiding',detail:'Turn a vague note into a quick conversation about intention.',consequence:'The question unlocks a better scene and makes this feel like a collaboration.',performance:5,relationship:6,industry:1,film:0,perception:'Thoughtful collaborator'},
 {label:'Trust the original instinct',detail:'Keep the interpretation that got you into the room.',consequence:'You make a clear artistic case. Nobody can accuse you of being forgettable.',performance:8,relationship:-5,industry:-2,film:0,perception:'Strong-willed'}];
const topics=[
 ['Performance','The director asks for a much bigger performance than the scene seems to hold.'],['Performance','The director asks you to strip away every visible emotion.'],['Performance','You and the director disagree about what the character knows.'],['Performance','A co-star improvises a crucial line and changes the scene.'],['Performance','The emotional scene is scheduled first thing, with no rehearsal.'],['Performance','Dialect sends a note questioning one vowel halfway through the shoot.'],['Performance','A child actor is tired and the difficult scene is losing focus.'],['Performance','Your co-star changes their performance completely on the close-up.'],
 ['Script','A rewrite removes the reason your character made sense to you.'],['Script','Four new pages arrive while lighting is being finished.'],['Script','The producer wants the exposition delivered much more clearly.'],['Script','The studio rewrite makes your character suddenly more violent.'],['Script','A romantic subplot has appeared after a nervous test screening.'],['Script','The ending is rewritten and your final scene is now ambiguous.'],
 ['Relationships','Your co-star is struggling and production is forty minutes behind.'],['Relationships','A famous co-star keeps improvising over your best line.'],['Relationships','The director’s frustration is turning personal.'],['Relationships','The producer gives you a note without telling the director.'],['Relationships','Another actor asks you to back them in a disagreement.'],['Relationships','The cinematographer quietly warns that the director is losing the crew.'],
 ['Physical','A stunt can be done practically, but the setup feels rushed.'],['Physical','The body double offers safety, but the close shot would sell the moment.'],['Physical','A physical sequence has changed with only an hour to prepare.'],['Physical','The assistant director wants one more take as weather worsens.'],['Physical','The location is freezing and continuity requires summer clothes.'],
 ['Career','Reshoots now clash with a meeting for a much bigger role.'],['Career','Publicity asks for a personal story you have never discussed publicly.'],['Career','Another actor drops out and the studio may expand your part.'],['Career','The studio wants a sequel option signed before anyone sees the film.'],['Career','The director quietly says they want you for their next project.'],['Career','A trade journalist asks about rumours of conflict on set.'],['Career','The network offers a longer contract with less freedom.']
];
export const productionTemplates=topics.map(([category,body],i)=>({id:`prod-${i}`,kind:'production' as const,kicker:`ON SET · ${category.toUpperCase()}`,title:['The note behind the note','Pages at breakfast','Pick your battle','One more take','A quiet request','The difficult version'][i%6],body,choices:[{label:'Protect the work',detail:'Make the artistic case, knowing the day and relationships have limits.',consequence:'The scene gains an edge, but the disagreement will be remembered.',performance:6,relationship:-4,industry:-1,film:5,perception:'Exacting about the work'},{label:'Find the compromise',detail:'Offer a practical version that gives everyone some of what they need.',consequence:'The day moves. Nobody gets everything; nobody feels ignored.',performance:3,relationship:4,industry:3,film:2,perception:'Reliable collaborator'},{label:'Back the people',detail:'Prioritise trust and safety over the most striking version of the scene.',consequence:'The crew notices the choice. The finished moment may be less spectacular.',performance:1,relationship:7,industry:2,film:-2,perception:'Generous scene partner'}]}));
export const careerEvents=[['A bigger agency calls','They promise better rooms and more attention. Marion does not pretend it is an easy choice.'],['The American question','Your agent can arrange Los Angeles meetings, but it means passing on a promising British limited series.'],['A useful pigeonhole','Casting has started describing you as “intense”. It is bringing work—and narrowing it.'],['The low-pay phone call','A director you trust has a passion project, a very good part and almost no money.'],['The publicity meeting','A weekend profile could raise your visibility, but the angle is more personal than you expected.'],['Two scripts, one window','A broad studio comedy and a tiny festival drama need the same six weeks.']];
