import type {AuditionStage,CareerState,EventChoice,Opportunity,Person,PersonRole,Project,ReleaseResult,StatKey,YearReview} from './types'
import * as d from './data'
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)))
export function random(state:{seed:number}){state.seed=(state.seed*1664525+1013904223)>>>0;return state.seed/4294967296}
const pick=<T>(s:{seed:number},a:T[])=>a[Math.floor(random(s)*a.length)]
const slug=(x:string)=>x.toLowerCase().replace(/[^a-z0-9]+/g,'-')
const person=(s:{seed:number},role:PersonRole):Person=>{const name=`${pick(s,d.firstNames)} ${pick(s,d.lastNames)}`;return{id:slug(`${role}-${name}`),name,role,quality:35+Math.floor(random(s)*50)}}
const months=['January','February','March','April','May','June','July','August','September','October','November','December']
const date=(s:CareerState)=>`${months[s.player.month]} ${s.player.year}`
const log=(s:CareerState,title:string,body:string,tone:'neutral'|'good'|'bad'='neutral',kind='CAREER NEWS')=>s.feed.unshift({id:`f-${s.seed}-${s.feed.length}`,date:date(s),title,body,tone,kind})
const remember=(s:CareerState,p:Person,warmth:number,line:string)=>{let r=s.relationships.find(x=>x.id===p.id);if(!r){r={...p,warmth:50,history:[],lastSeen:s.player.year};s.relationships.push(r)}r.warmth=clamp(r.warmth+warmth);r.lastSeen=s.player.year;r.history.push(line)}
const newYearStats=(year:number):YearReview=>({year,filmed:0,released:0,earnings:0,relationships:0})
const advance=(s:CareerState,n:number)=>{const before=s.player.year;s.player.month+=n;while(s.player.month>11){s.player.month-=12;s.player.year++;s.player.age++}if(s.player.year>before&&s.phase==='opportunities'&&s.yearStats.year===before){s.event={id:'year-review',kind:'year',kicker:`${before} · YEAR IN REVIEW`,title:'A year in the work',body:'The useful version of the annual reckoning: what got made, what connected and what changed.',choices:[]};s.phase='yearReview'}}
function project(s:CareerState,index:number):Project{
 const [genre,subgenre]=pick(s,d.genres);const standing=s.player.stats.industry;const roll=random(s);const roleSize=standing>65&&roll<.3?'Lead':standing>34&&roll<.35?'Major supporting':roll<.18?'Recurring':roll<.52?'Supporting':'Day player';
 const type=random(s)<.48?'Film':random(s)<.72?'TV':'Limited series';const format=type==='Film'?'Feature film':type==='TV'?`${3+Math.floor(random(s)*6)}-episode series`:`${3+Math.floor(random(s)*4)}-part limited series`;const budget=Math.round((type==='Film'?2+random(s)*78:.8+random(s)*14)*10)/10;const director=returningOrNew(s,'Director');const castingDirector=returningOrNew(s,'Casting Director');const producer=person(s,'Producer');
 const directChance=standing<25?.01:standing<50?.12:standing<70?.32:.58;const offerType=random(s)<directChance?(standing>62&&random(s)<.6?'Direct offer':'Meeting'):'Audition';const title=pick(s,d.titles);const coStars=[person(s,'Actor').name,person(s,'Actor').name];
 return{id:`p-${s.seed}-${index}`,title,type,format,genre,subgenre,studio:pick(s,d.studios),director,producer,castingDirector,role:pick(s,d.roles),character:pick(s,d.roleDescriptions),roleSize,budget,salary:Math.round((800+budget*260+({Lead:18000,'Major supporting':8000,Supporting:2800,Recurring:2200,'Day player':0}[roleSize]||0))/100)*100,weeks:Math.max(1,Math.round((roleSize==='Lead'?8:roleSize==='Major supporting'?5:roleSize==='Supporting'?3:1)+random(s)*3)),script:pick(s,d.scripts),agentRead:pick(s,d.agentReads),logline:pick(s,d.loglines),coStars,offerType,hidden:{script:20+random(s)*76,appeal:20+random(s)*76,chaos:random(s)*85,director:director.quality},history:[]}
}
function returningOrNew(s:CareerState,role:PersonRole){const warm=s.relationships.filter(r=>r.role===role&&r.warmth>55);if(warm.length&&random(s)<.24){const old=pick(s,warm);old.quality=clamp(old.quality+(s.player.year-(old.lastSeen||s.player.year)));return{id:old.id,name:old.name,role:old.role,quality:old.quality}}return person(s,role)}
function routeFor(p:Project):AuditionStage[]{if(p.offerType==='Direct offer')return ['Result'];if(p.roleSize==='Day player')return ['Self-tape','Callback','Result'];if(p.roleSize==='Supporting'||p.roleSize==='Recurring')return ['Self-tape','Callback','Director session','Result'];return ['Self-tape','Callback',randomStage(p),'Screen test','Final two','Result']}
const randomStage=(p:Project):AuditionStage=>p.genre.includes('Romantic')?'Chemistry read':p.type==='Film'?'Chemistry read':'Director session'
export function newCareer(name:string,pronouns:string,seed=Date.now()>>>0):CareerState{const year=2026;const s:CareerState={version:2,seed,player:{name,pronouns,age:24,year,month:0,money:1800,earnings:0,agent:'Marion Pike · Pike & Rowe',agentQuality:28,stats:{industry:8,critical:4,audience:1,commercial:1},abilities:{drama:56,comedy:52,audition:48,technical:54,physical:50},perceptions:['Unproven','Good training, little footage']},opportunities:[],productionQueue:[],productionPerformance:50,filmQuality:50,filmography:[],relationships:[{id:'agent-marion-pike',name:'Marion Pike',role:'Agent',quality:28,warmth:64,history:['Signed you after a well-reviewed drama-school showcase.'],lastSeen:year}],feed:[],cycle:0,phase:'opportunities',awards:[],lastReviewYear:year-1,yearStats:newYearStats(year)};log(s,'Marion has three scripts',`You have two short-film credits and a headshot everyone calls “versatile”. Ordinary months happen off-screen; only the consequential ones reach this desk.`);generateOpportunities(s);return s}
export function generateOpportunities(s:CareerState){s.opportunities=Array.from({length:3},(_,i)=>{const p=project(s,i);return{project:p,stages:routeFor(p),stageIndex:0,status:p.offerType==='Direct offer'?'offered':'open',prepared:false,competitor:person(s,'Actor').name,performance:45+random(s)*15,professionalism:50,chemistry:50,history:[]} as Opportunity});s.phase='opportunities';s.event=undefined;s.cycle++;log(s,'Your agent is calling',`${s.opportunities.length} projects have become real enough to discuss. The slate is deliberately varied; you can prepare deeply for one.`,'neutral','NEW SCRIPTS')}
export function resolveAuditions(s:CareerState,preparedId:string){advance(s,2);if(s.phase==='yearReview')return;s.opportunities.forEach(o=>{o.prepared=o.project.id===preparedId;o.performance+=(o.prepared?14:0)+(random(s)-.5)*18;if(o.status==='offered')return;const pass=o.performance+s.player.stats.industry*.18+s.player.agentQuality*.08>49+random(s)*44;if(!pass){reject(s,o,'Self-tape',false)}else{o.status='active';o.stageIndex=1;o.history.push({stage:'Self-tape',note:'The first read landed.',outcome:'Invited back.'})}});const active=s.opportunities.filter(o=>o.status==='active');if(active.length){s.phase='audition';queueAudition(s,active[0])}else{const offered=s.opportunities.find(o=>o.status==='offered');if(offered)offerEvent(s,offered);else log(s,'The slate closes','No booking this time. One casting office sends a proper note rather than the usual silence. That counts for something.','bad','AUDITION RESULT')}}
function queueAudition(s:CareerState,o:Opportunity){const stage=o.stages[o.stageIndex];s.currentOpportunity=o;const late=stage==='Final two';s.event={id:`aud-${o.project.id}-${stage}`,kind:'audition',kicker:late?'FINAL TWO':stage.toUpperCase(),title:o.project.title,body:late?`The director prefers you. The producer is nervous about your credits. You read opposite ${o.project.coStars[0]} tomorrow.`:`${pick(s,d.auditionNotes)} This is the ${stage.toLowerCase()} for ${o.project.role}.`,projectId:o.project.id,choices:d.auditionChoices}}
function offerEvent(s:CareerState,o:Opportunity){s.currentOpportunity=o;s.phase='audition';s.event={id:`offer-${o.project.id}`,kind:'audition',kicker:'DIRECT OFFER',title:o.project.title,body:`${o.project.director.name} wants you for ${o.project.role}. No tape—just a conversation and a decision.`,projectId:o.project.id,choices:[{label:'Accept the part',detail:`Commit ${o.project.weeks} weeks to the project.`,consequence:'Your agent closes the deal. The call sheet arrives that afternoon.',performance:3,relationship:5,industry:2,film:0},{label:'Ask for a meeting first',detail:'Understand the director’s intentions before saying yes.',consequence:'The conversation is frank and useful. They respect the question.',performance:4,relationship:3,industry:1,film:1},{label:'Pass gracefully',detail:'Leave the relationship intact and keep the dates open.',consequence:'Marion declines without manufacturing an excuse.',performance:0,relationship:0,industry:0,film:0}]}}
export function chooseStory(s:CareerState,index:number){if(!s.event)return;if(s.event.kind==='year'){s.lastReviewYear=s.yearStats.year;s.yearStats=newYearStats(s.player.year);s.phase='opportunities';s.event=undefined;generateOpportunities(s);return}const c=s.event.choices[index];if(s.event.kind==='audition')advanceAudition(s,c,index);else if(s.event.kind==='career')advanceCareer(s,c);else advanceProduction(s,c)}
function advanceCareer(s:CareerState,c:EventChoice){s.player.stats.industry=clamp(s.player.stats.industry+c.industry);if(c.perception&&!s.player.perceptions.includes(c.perception))s.player.perceptions.push(c.perception);remember(s,s.relationships.find(r=>r.role==='Agent')!,c.relationship,`${c.label}: ${c.consequence}`);log(s,c.label,c.consequence,'neutral','CAREER DECISION');s.event=undefined;s.phase='opportunities';generateOpportunities(s)}
function advanceAudition(s:CareerState,c:EventChoice,index:number){const o=s.currentOpportunity!;o.performance+=c.performance;o.professionalism+=c.industry;o.chemistry+=c.relationship;o.history.push({stage:o.stages[o.stageIndex]||'Result',note:s.event!.body,choice:c.label,outcome:c.consequence});o.project.history.push(`${s.event!.kicker}: ${c.label}. ${c.consequence}`);remember(s,o.project.director,c.relationship,`${c.consequence} (${o.project.title}, ${s.player.year})`);if(o.status==='offered'){if(index===2){o.status='rejected';log(s,`You pass on ${o.project.title}`,c.consequence,'neutral','CAREER DECISION');finishAuditionSlate(s);return}book(s,o);return}o.stageIndex++;const next=o.stages[o.stageIndex];if(next==='Result'){const score=o.performance+s.player.stats.industry*.2+o.chemistry*.08;const booked=score>57+random(s)*48;if(booked)book(s,o);else reject(s,o,o.stages[o.stageIndex-1],true);return}const survival=o.performance+o.professionalism*.08+(o.prepared?3:0)>47+random(s)*48;if(!survival){reject(s,o,o.stages[o.stageIndex-1],o.stageIndex>=o.stages.length-2);return}queueAudition(s,o)}
function reject(s:CareerState,o:Opportunity,stage:AuditionStage,close:boolean){o.status='rejected';o.history.push({stage,note:'The process ended here.',outcome:close?`${o.competitor} was cast. The director asked casting to keep you in mind.`:'Casting went another way.'});o.project.history.push(close?`Reached ${stage}; ${o.competitor} was cast. ${o.project.director.name} asked to keep you in mind.`:`The audition ended at ${stage}.`);if(close){remember(s,o.project.director,5,`Liked your ${stage.toLowerCase()} for ${o.project.title}, despite casting ${o.competitor}.`);remember(s,o.project.castingDirector,7,`Brought you to ${stage.toLowerCase()} for ${o.project.title}.`)}log(s,`You didn't get ${o.project.title}`,close?`${o.competitor} got the part. ${o.project.director.name} asked casting to keep you on file.`:'The email is polite and brief. This one ends here.',close?'neutral':'bad','AUDITION RESULT');finishAuditionSlate(s)}
function finishAuditionSlate(s:CareerState){const next=s.opportunities.find(o=>o.status==='active');if(next)queueAudition(s,next);else{const offered=s.opportunities.find(o=>o.status==='offered');if(offered)offerEvent(s,offered);else{s.phase='opportunities';s.event=undefined;s.currentOpportunity=undefined}}}
function book(s:CareerState,o:Opportunity){o.status='booked';o.project.history.push(`Cast as ${o.project.role} after ${o.history.map(h=>h.stage).join(' → ')}.`);s.current=o.project;s.currentOpportunity=o;s.player.money+=o.project.salary;s.player.earnings+=o.project.salary;s.yearStats.filmed++;s.yearStats.earnings+=o.project.salary;remember(s,o.project.director,7,`Cast you as ${o.project.role} in ${o.project.title}.`);remember(s,o.project.castingDirector,5,`Cast you in ${o.project.title}.`);log(s,`Booked: ${o.project.title}`,`${o.project.studio} offers £${o.project.salary.toLocaleString()} for ${o.project.weeks} weeks. The job now has to become a piece of work.`,'good','BOOKING');startProduction(s)}
function eventCount(p:Project){return p.roleSize==='Lead'?Math.min(5,p.budget>40?5:4):p.roleSize==='Major supporting'?3:p.roleSize==='Supporting'?2:p.roleSize==='Recurring'?2:1}
function startProduction(s:CareerState){s.phase='production';s.productionPerformance=50+random(s)*14;s.filmQuality=50;s.productionQueue=[];const pool=[...d.productionTemplates];for(let i=0;i<eventCount(s.current!);i++)s.productionQueue.push(pool.splice(Math.floor(random(s)*pool.length),1)[0]);s.event=s.productionQueue.shift()}
function advanceProduction(s:CareerState,c:EventChoice){const p=s.current!;s.productionPerformance+=c.performance;s.filmQuality+=c.film;p.history.push(`${s.event!.title}: ${c.label}. ${c.consequence}`);remember(s,p.director,c.relationship,`${c.label} during ${p.title}: ${c.consequence}`);s.player.stats.industry=clamp(s.player.stats.industry+c.industry);if(c.perception&&!s.player.perceptions.includes(c.perception))s.player.perceptions.push(c.perception);log(s,c.label,c.consequence,c.relationship<0?'bad':'good',s.event!.kicker);if(s.productionQueue.length)s.event=s.productionQueue.shift();else{s.event=undefined;s.phase='release';advance(s,Math.max(3,p.weeks>6?7:5))}}
export function releaseProject(s:CareerState){if(!s.current)return;const p=s.current;const critic=clamp(p.hidden.script*.48+p.hidden.director*.19+s.filmQuality*.24+(random(s)-.5)*38-p.hidden.chaos*.1);const audience=clamp(p.hidden.appeal*.45+critic*.28+(random(s)-.5)*40);const acting=clamp(s.productionPerformance+(random(s)-.5)*34);const worldwide=Math.max(.1,Math.round((p.budget*(.25+audience/45)*(p.type==='Film'?1:.25))*10)/10);const boxOffice=p.type!=='Film'?(audience>72?'Breakout audience hit':audience<38?'Quietly cancelled':'Steady audience'):worldwide>p.budget*2.3?'Surprise hit':worldwide>p.budget*1.45?'Commercial hit':worldwide<p.budget*.65?'Box-office bomb':'Modest result';const performance=acting>78?'Outstanding notices':acting>64?'Strong notices':acting<38?'Performance criticised':'Mixed-to-positive notices';const impact:Partial<Record<StatKey,number>>={critical:acting>70?6:acting<40?-2:1,industry:acting>66?5:acting<40?-2:2,audience:audience>68?6:audience<35?0:2,commercial:boxOffice.includes('hit')?7:boxOffice.includes('bomb')?-3:1};Object.entries(impact).forEach(([k,v])=>s.player.stats[k as StatKey]=clamp(s.player.stats[k as StatKey]+(v||0)));const award=critic>82&&acting>75&&random(s)<.35?'Independent Screen Prize nomination':undefined;if(award)s.awards.push(`${s.player.year} · ${award} · ${p.title}`);const consensus=critic>72?'The film has rough edges, but its best scenes feel observed rather than manufactured.':critic<40?'A muddled production with flashes of the sharper film it might have been.':'Uneven, watchable and carried by a handful of committed performances.';const release:ReleaseResult={critic,audience,performance,performanceScore:acting,boxOffice,worldwide,consensus,reviews:[pick(s,d.reviewSnippets),pick(s,d.reviewSnippets),acting>critic+8?`“${s.player.name} is one of the few things that works.”`:pick(s,d.reviewSnippets)],impact,award};p.history.push(`Released to ${critic} from critics and ${audience/10}/10 from audiences. ${performance}. ${boxOffice}.`);const credit={project:p,release,year:s.player.year};s.filmography.push(credit);s.lastRelease=credit;s.yearStats.released++;if(!s.yearStats.best||critic>60)s.yearStats.best=p.title;if(critic<45)s.yearStats.disappointment=p.title;s.current=undefined;s.currentOpportunity=undefined;s.phase='opportunities';log(s,'The reviews are in',`${p.title}: ${performance.toLowerCase()}. ${boxOffice}. The film and your work do not necessarily share the same fate.`,critic>65?'good':critic<40?'bad':'neutral','RELEASE')}
export function nextCycle(s:CareerState){advance(s,2);if(s.phase==='yearReview')return;if(random(s)<.28){const [title,body]=pick(s,d.careerEvents);s.event={id:`career-${s.seed}`,kind:'career',kicker:'YOUR AGENT IS CALLING',title,body,choices:[{label:'Take the ambitious route',detail:'Accept the exposure and the uncertainty that comes with it.',consequence:'You choose momentum over comfort. The industry notices; Marion worries about the downside.',performance:0,relationship:-2,industry:3,film:0,perception:'Career risk-taker'},{label:'Protect the long game',detail:'Prioritise trusted collaborators and control over a quick leap.',consequence:'It is the less dramatic choice, but the relationship strengthens.',performance:0,relationship:6,industry:0,film:0,perception:'Loyal collaborator'},{label:'Negotiate a third way',detail:'Ask Marion to preserve options rather than accept the forced choice.',consequence:'The compromise costs some momentum and keeps more doors open.',performance:0,relationship:3,industry:1,film:0,perception:'Careful strategist'}]}}else generateOpportunities(s)}
export const reputationTier=(key:StatKey,n:number)=>({industry:n>74?'Highly regarded':n>52?'Established':n>28?'Working actor':n>12?'Emerging':'Unknown',critical:n>74?'Acclaimed':n>50?'Well reviewed':n>24?'Promising':'No track record',audience:n>75?'Widely known':n>52?'Recognisable':n>25?'Familiar face':'None',commercial:n>75?'Bankable':n>52?'Proven lead':n>25?'Useful draw':'None'}[key])
export const relationshipTier=(n:number)=>n>78?'Strong advocate':n>62?'Warm':n>45?'Professional':n>31?'Cool':n>17?'Strained':'Hostile'
export const careerStatus=(s:CareerState)=>s.player.stats.audience>70?'Recognisable star':s.player.stats.critical>55?'Highly regarded performer':s.filmography.length>6?'Established working actor':s.filmography.length>1?'Working actor':'Unknown actor'
export function migrateSave(raw:unknown):CareerState{const old=raw as Partial<CareerState>;if(old.version===2)return old as CareerState;const fresh=newCareer(old.player?.name||'Alex Morgan',old.player?.pronouns||'they/them',old.seed||12345);if(old.player)fresh.player={...fresh.player,...old.player,stats:{...fresh.player.stats,...old.player.stats}};fresh.filmography=old.filmography||[];fresh.relationships=(old.relationships||fresh.relationships).map(r=>({...r,lastSeen:r.lastSeen||fresh.player.year}));fresh.awards=old.awards||[];fresh.feed=[...(old.feed||[]),...fresh.feed];return fresh}
