import type {CareerState,Opportunity,Person,Project,ProductionEvent,ReleaseResult,StatKey} from './types';
import * as d from './data';
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
export function random(state:{seed:number}){state.seed=(state.seed*1664525+1013904223)>>>0;return state.seed/4294967296}
const pick=<T>(s:{seed:number},a:T[])=>a[Math.floor(random(s)*a.length)];
const person=(s:{seed:number},role:Person['role']='Director'):Person=>{const name=`${pick(s,d.firstNames)} ${pick(s,d.lastNames)}`;return{id:name.toLowerCase().replace(/ /g,'-'),name,role,quality:35+Math.floor(random(s)*45)}};
const date=(s:CareerState)=>`${['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][s.player.month]} ${s.player.year}`;
const log=(s:CareerState,title:string,body:string,tone:'neutral'|'good'|'bad'='neutral')=>s.feed.unshift({id:`f${s.seed}-${s.feed.length}`,date:date(s),title,body,tone});
const advance=(s:CareerState,months:number)=>{s.player.month+=months;while(s.player.month>11){s.player.month-=12;s.player.year++;s.player.age++;}};
function makeProject(s:CareerState,index:number):Project{const genre=pick(s,['Drama','Comedy','Crime','Horror','Thriller']);const type=random(s)<.58?'TV':'Film';const roleSize=s.player.stats.industry>35&&random(s)<.3?'Supporting':random(s)<.22?'Recurring':'Day Player';const budget=type==='TV'?Math.round((.8+random(s)*5)*10)/10:Math.round((1+random(s)*11)*10)/10;const director=person(s);return{id:`p${s.seed}-${index}`,title:`${pick(s,d.titleA)} ${pick(s,d.titleB)}`,type,genre,studio:pick(s,d.studios),director,role:pick(s,d.roles),roleSize,budget,salary:Math.round((900+budget*350+(roleSize==='Supporting'?2200:0))/100)*100,weeks:1+Math.floor(random(s)*5),script:pick(s,d.scripts),coStar:`${pick(s,d.firstNames)} ${pick(s,d.lastNames)}`,hidden:{script:20+random(s)*75,appeal:20+random(s)*75,chaos:random(s)*80,director:director.quality},history:[]};}
export function newCareer(name:string,pronouns:string,seed=Date.now()>>>0):CareerState{const s:CareerState={seed,player:{name,pronouns,age:24,year:2026,month:0,money:1800,earnings:0,agent:'Marion Pike · Pike & Rowe',agentQuality:28,stats:{industry:8,critical:4,audience:1,commercial:1},abilities:{drama:56,comedy:52,audition:48,technical:54,physical:50},perceptions:['Unproven','Good training, little footage']},opportunities:[],productionPerformance:0,filmography:[],relationships:[{id:'marion-pike',name:'Marion Pike',role:'Agent',quality:28,warmth:62,history:['Signed you after a well-reviewed drama-school showcase.']}],feed:[],cycle:0,phase:'opportunities',awards:[]};log(s,'Welcome to the glamorous bit before the glamour','You have two short-film credits, a small agent, and a headshot that everyone agrees is “versatile”. Ordinary bills happen off-screen.');generateOpportunities(s);return s;}
export function generateOpportunities(s:CareerState){s.opportunities=Array.from({length:3},(_,i):Opportunity=>({project:makeProject(s,i),stage:0,status:'open',prepared:false,competitor:pick(s,d.competitors)}));s.phase='opportunities';s.cycle++;log(s,'Three months, eleven auditions',`Most went nowhere. ${s.opportunities.length} have become serious enough to deserve your attention. You have time to heavily prepare for one.`);}
export function resolveAuditions(s:CareerState,preparedId:string){advance(s,3);let booked:Opportunity|undefined;s.opportunities.forEach(o=>{o.prepared=o.project.id===preparedId;const fit=45+(o.project.genre==='Drama'?(s.player.abilities.drama-50):o.project.genre==='Comedy'?(s.player.abilities.comedy-50):0);const relationship=s.relationships.find(r=>r.id===o.project.director.id)?.warmth||50;const chance=clamp(18+(fit-45)*.5+s.player.stats.industry*.35+s.player.agentQuality*.15+(o.prepared?19:0)+(relationship-50)*.15);o.chance=chance;const roll=random(s)*100;if(!booked&&roll<chance){o.status='booked';o.stage=3;booked=o;o.project.history.push(`After an initial read and callback, you beat ${o.competitor} to the role.`)}else{o.status='rejected';o.stage=roll<chance+25?2:roll<chance+45?1:0;o.project.history.push(o.stage===2?`You reached the final two, but ${o.competitor} booked it.`:`The audition ended at the ${o.stage?'callback':'first read'}.`);log(s,`You didn't get ${o.project.title}`,o.stage===2?`${o.competitor} got the call. The casting director says it was very close.`:'A polite email arrives. No notes, naturally.','bad')}});if(booked){startProduction(s,booked.project)}else{log(s,'No booking this round','Not a catastrophe, but your agent has started using the phrase “keep the faith”. Time moves on.','bad')}}
function startProduction(s:CareerState,p:Project){s.current=p;s.phase='production';s.productionPerformance=50+random(s)*16;s.player.money+=p.salary;s.player.earnings+=p.salary;const existing=s.relationships.find(r=>r.id===p.director.id);if(!existing)s.relationships.push({...p.director,warmth:50,history:[`Cast you as ${p.role} in ${p.title}.`]});s.productionEvent=makeEvent(s);log(s,`Booked: ${p.title}`,`${p.studio} offers £${p.salary.toLocaleString()} for ${p.weeks} week${p.weeks>1?'s':''}. It is your first proper ${p.roleSize.toLowerCase()} credit.`,'good');}
function makeEvent(s:CareerState):ProductionEvent{const events=[{title:'The note behind the note',body:'The director asks you to play the scene much broader. You think it makes the character less believable.',choices:[{label:'Trust the director',detail:'Be adaptable, even if the scene loses subtlety.',performance:-3,relationship:9,industry:3},{label:'Make the case once',detail:'Offer a specific alternative, then accept the decision.',performance:5,relationship:1,industry:1,perception:"Director's actor"},{label:'Hold your ground',detail:'Protect the performance and risk slowing the day.',performance:9,relationship:-10,industry:-3,perception:'Strong-willed'}]},{title:'A co-star is drowning',body:'Your co-star is struggling with a rewritten scene. Production is already forty minutes behind.',choices:[{label:'Quietly run lines',detail:'Give up your lunch to help without making a show of it.',performance:4,relationship:6,industry:2,perception:'Generous scene partner'},{label:'Stay out of it',detail:'They are a professional. Protect your own preparation.',performance:3,relationship:-2,industry:0},{label:'Suggest improvising',detail:'Could unlock the scene. Could also make continuity furious.',performance:7,relationship:4,industry:-2,perception:'Strong improviser'}]}];return pick(s,events)}
export function chooseProduction(s:CareerState,index:number){if(!s.current||!s.productionEvent)return;const c=s.productionEvent.choices[index];s.productionPerformance+=c.performance;s.player.stats.industry=clamp(s.player.stats.industry+c.industry);const rel=s.relationships.find(r=>r.id===s.current!.director.id);if(rel){rel.warmth=clamp(rel.warmth+c.relationship);rel.history.push(`${c.label} during ${s.current.title} (${c.relationship>=0?'+':''}${c.relationship}).`)}if(c.perception&&!s.player.perceptions.includes(c.perception))s.player.perceptions.push(c.perception);s.current.history.push(`${s.productionEvent.title}: ${c.label}. ${c.detail}`);log(s,c.label,c.detail,c.relationship>=0?'good':'bad');s.productionEvent=undefined;s.phase='release';advance(s,6);}
export function releaseProject(s:CareerState){if(!s.current)return;const p=s.current;const critic=clamp(p.hidden.script*.5+p.hidden.director*.25+s.productionPerformance*.15+(random(s)-.5)*35-p.hidden.chaos*.12);const audience=clamp(p.hidden.appeal*.48+critic*.25+(random(s)-.5)*38);const ratio=(audience+p.hidden.appeal)/(p.budget*12+35);const performance=critic>78?'The reviews are excellent.':critic<40?'Critics are not kind.':'Reviews are mixed, with a few enthusiastic holdouts.';const boxOffice=ratio>2.2?'Surprise hit':ratio>1.25?'Solid result':ratio<.7?'Financial flop':'Disappointing';const acting=clamp(s.productionPerformance+(random(s)-.5)*28);const impact:Partial<Record<StatKey,number>>={critical:critic>70?6:critic<38?-2:1,industry:acting>68?5:acting<38?-2:2,audience:audience>65?5:1,commercial:boxOffice==='Surprise hit'?6:boxOffice==='Financial flop'?-3:1};Object.entries(impact).forEach(([k,v])=>s.player.stats[k as StatKey]=clamp(s.player.stats[k as StatKey]+(v||0)));const award=critic>84&&acting>76&&random(s)<.3?'Independent Screen Prize nomination':undefined;if(award)s.awards.push(`${s.player.year} · ${award} · ${p.title}`);const release:ReleaseResult={critic,audience,performance,boxOffice,impact,award};p.history.push(`${performance} Audience response: ${audience}. Commercial result: ${boxOffice}.`,acting>critic?`Even sceptical reviews single out ${s.player.name}.`:`Your notices are broadly in line with the film.`);const credit={project:p,release,year:s.player.year};s.filmography.push(credit);s.lastRelease=credit;log(s,`${p.title} is released`,`${performance} ${boxOffice}. ${acting>critic+8?'Several critics say you are one of the things that works.':'Your performance receives its share of the response.'}`,critic>60?'good':critic<40?'bad':'neutral');s.current=undefined;s.phase='opportunities';}
export function nextCycle(s:CareerState){advance(s,2);if(s.player.age>=40){log(s,'A career, not a tutorial',`At 40, you have ${s.filmography.length} substantial credits and £${s.player.earnings.toLocaleString()} in career earnings. You can keep playing this prototype, but the first chapter is complete.`)}generateOpportunities(s)}
export const careerStatus=(s:CareerState)=>s.player.stats.audience>65?'Recognisable star':s.player.stats.critical>55?'Prestige performer':s.filmography.length>7?'Established working actor':s.filmography.length>2?'Working actor':'Unknown actor';
